CHECK_DOCUMENT_TYPE = """Beschouw de volgende tekst tussen triple quotes: '''{document_text}'''
Check het type van het document. Is dit een vaststellingsovereenkomst, een arbeidsovereenkomst, een loonstrook of een ander type?
Retourneer alleen het type van het document als een string. Geef geen verdere output"""

ANALYZE_DOCUMENT = """Beschouw de volgende tekst tussen triple quotes: '''{document_text}'''
Extraheer de volgende zaken uit de tekst:
{checks}
Als een zaak niet aanwezig is, geef dan een lege string terug.
Antwoord in het volgende formaat:\n{answer_format}etc..
Belangrijk! Antwoord alleen in bovenstaand formaat. Geef geen extra informatie terug."""

MISSING_DATA = "<p>Vul de volgende gegevens aan:<ul>{missing_data_sentence}</ul></p>"

MISSING_CLAUSES = """<p>Let erop dat de volgende zaken in de Vaststellingsovereenkomst zijn opgenomen:
<ul>{missing_clauses_sentence}</ul></p>"""

DATES_MISSING = "<p>Om de opzegtermijn te kunnen checken moeten zowel opzegdatum als einddatum zijn ingevuld.</p>"

TERMINATION_TERM_DETAILS = """<p>De opzegtermijn voldoet niet aan de wettelijke eisen.<br/>
De door de werkgever in acht te nemen termijn van opzegging bedraagt bij een arbeidsovereenkomst die op de dag van opzegging:
<ol>
    <li>korter dan vijf jaar heeft geduurd: één maand;</li>
    <li>vijf jaar of langer, maar korter dan tien jaar heeft geduurd: twee maanden;</li>
    <li>tien jaar of langer, maar korter dan vijftien jaar heeft geduurd: drie maanden;</li>
    <li>vijftien jaar of langer heeft geduurd: vier maanden.</li>
</ol></p>"""

NO_ADVICE = '<p>Deze vaststellingsovereenkomst lijkt helemaal in orde.</p>'

EXTRACT_DATE_FORMAT = """Bij {fields} extraheer de datum in het formaat "yyyy-mm-dd".
Lukt dat niet, geef dan een lege string terug."""