#[TYPE_OVEREENKOMST]
#description = "Het type van de overeenkomst"
#options = ["vaststellingsovereenkomst", "arbeidsovereenkomst", "anders"]
#prompt = "is dit een vaststellingsovereenkomst, arbeidsoverkomst of anders?"

[NAAM_WERKGEVER]
description = "Naam werkgever"
prompt = "de naam de werkgever"

[ADRES_WERKGEVER]
description = "Adres werkgever"
prompt = "het adres van de werkgever"

[NAAM_WERKNEMER]
description = "Naam werknemer"
prompt = "de naam van de werknemer"

[ADRES_WERKNEMER]
description = "Adres werknemer"
prompt = "het adres van de werknemer"

[SALARIS]
description = "Salaris"
prompt = "het salaris van de werknemer"

[VOORGESTELD]
options = ["ja", "nee"]
description = "Werkgever heeft voorgesteld arbeidsovereenkomst te beëindigen."
prompt = "dat werkgever voorgesteld om de arbeidsovereenkomst te beëindigen en dat het initiatief dus echt bij de werkgever ligt."

[REDEN]
description = "Reden beëindiging"
prompt = "de reden voor de beëindiging"

[GEEN_VERWIJT]
options = ["ja", "nee"]
description = "Werknemer kan geen verwijt worden gemaakt"
prompt = "dat werknemer geen verwijt kan worden gemaakt"

[DRINGENDE_REDEN]
options = ["ja", "nee"]
description = "Geen dringende reden voor ontslag"
prompt = "dat er geen dringende reden voor het ontslag is"

[OPZEGVERBOD]
options = ["ja", "nee"]
description = "Geen opzegverbod"
prompt = "dat er geen opzegverbod van toepassing is; antwoord alleen 'ja' als expliciet genoemd wordt dat er geen opzegverbod van toepassing is"

[WEDERZIJDS_GOEDVINDEN]
options = ["ja", "nee"]
description = "Beëindiging met wederzijds goedvinden"
prompt = "dat het gaat om een beëindiging met wederzijds goedvinden"

[RELATIEBEDING]
options = ["vervallen", "niet vervallen", "niet van toepassing"]
description = "Relatiebeding"
prompt = "dat het relatiebeding vervalt, niet vervalt of niet van toepassing is"
required = false

[CONCURRENTIEBEDING]
options = ["vervallen", "niet vervallen", "niet van toepassing"]
description = "Concurrentiebeding"
prompt = "dat het concurrentiebeding vervalt, niet vervalt of niet van toepassing is"
required = false

[PENSIOENREGELING]
options = ["ja", "nee", "niet van toepassing"]
description = "Pensioenregeling"
prompt = "dat als er een pensioenregeling is, deze tot het eind wordt nagekomen"
required = false

[EINDDATUM]
type = "datum"
description = "Datum einde arbeidsovereenkomst"
prompt = "de datum waarop de arbeidsovereenkomst eindigt"

[EINDAFREKENING]
type = "datum"
description = "Datum eindafrekening"
prompt = "op welke datum werkgever een eindafrekening maakt"

[BEDENKTIJD]
options = ["ja", "nee"]
description = "Twee weken bedenktijd"
prompt = "dat de werknemer twee weken bedenktijd heeft (denk goed na, bekijk eerst zelf of er wel een bedenktijd wordt genoemd en zo ja: welke bedenktijd)"

[PLAATS_ONDERTEKENING]
description = "Plaats van ondertekening"
prompt = "waar werkgever en werknemer de overeenkomst hebben ondertekend"

[DATUM_ONDERTEKENING]
type = "datum"
description = "Datum van ondertekening datum"
prompt = "wanneer werkgever en werknemer de overeenkomst hebben ondertekend"
